# Generated by Django 5.0.9 on 2025-04-09 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from urllib.parse import urlparse


def create_default_wikibase(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Wikibase = apps.get_model("core", "Wikibase")
    if not Wikibase.objects.using(db_alias).exists():
        url = settings.DEFAULT_WIKIBASE_URL if settings.DEFAULT_WIKIBASE_URL else "https://test.wikidata.org"
        parsed_root_enpoint = urlparse(url)
        default_wikibase_url = f"{parsed_root_enpoint.scheme}://{parsed_root_enpoint.netloc}"
        wikibase = Wikibase.objects.using(db_alias).create(url=default_wikibase_url)
    Batch = apps.get_model("core", "Batch")
    for b in Batch.objects.using(db_alias).all():
        b.wikibase = wikibase
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_batchcommand_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikibase',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('identifier', models.SlugField(default='wikidata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='wikibase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wikibase'),
        ),
        migrations.RunPython(
            code=create_default_wikibase,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='batch',
            name='wikibase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wikibase'),
        ),
    ]
