# Generated by Django 5.0.9 on 2025-04-09 08:02

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_batchcommand_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikibase',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('identifier', models.SlugField(default='wikidata', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='wikibase',
            field=models.ForeignKey(default=core.models.get_default_wikibase, on_delete=django.db.models.deletion.CASCADE, to='core.wikibase'),
        ),
    ]
