# Generated by Django 5.0.9 on 2025-03-27 10:52

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_batchcommand_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wikibase',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='wikibase',
            field=models.ForeignKey(default=core.models.get_default_wikibase, on_delete=django.db.models.deletion.CASCADE, to='core.wikibase'),
        ),
    ]
