# Generated by Django 5.0.9 on 2025-04-10 12:42

from django.db import migrations


def move_web_tokens_to_core(apps, schema_editor):
    WebToken = apps.get_model("web", "Token")
    Token = apps.get_model("core", "Token")

    for web_token in WebToken.objects.all():
        Token.objects.create(
            user=web_token.user,
            value=web_token.value,
            refresh_token=web_token.refresh_token,
            expires_at=web_token.expires_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_wikibase_token_batch_wikibase"),
        ("web", "0004_token_expires_at_token_refresh_token"),
    ]

    operations = [
        migrations.RunPython(
            code=move_web_tokens_to_core, reverse_code=migrations.RunPython.noop
        )
    ]
