# Generated by Django 5.0.9 on 2025-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_move_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcommand',
            name='response_id',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
