# Generated by Django 5.0.9 on 2025-04-23 15:51

from django.db import migrations


def set_response_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    BatchCommand = apps.get_model("core", "BatchCommand")

    for command in BatchCommand.objects.using(db_alias).filter(
        response_json__id__isnull=False
    ).iterator():
        command.response_id = command.response_json.get("id")
        command.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_batchcommand_response_id"),
    ]

    operations = [
        migrations.RunPython(
            code=set_response_id, reverse_code=migrations.RunPython.noop, elidable=True
        )
    ]
