# Generated by Django 5.0.9 on 2025-04-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_set_response_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcommand',
            name='response_json',
        ),
    ]
