# Generated by Django 5.0.9 on 2025-05-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_batchcommand_response_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.userbatch'),
        ),
    ]
