# Generated by Django 5.0.9 on 2025-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_batchcommand_response_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikibase',
            options={'ordering': ('listing_order',)},
        ),
        migrations.AddField(
            model_name='wikibase',
            name='has_discussion_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wikibase',
            name='listing_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
