# Generated by Django 5.0.9 on 2025-05-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_wikibase_options_wikibase_has_discussion_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEditingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editing_session', to='core.batch')),
            ],
        ),
    ]
