# Generated by Django 5.0.9 on 2025-05-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_batcheditingsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchcommand',
            options={'ordering': ('batch', 'index'), 'verbose_name': 'Batch Command', 'verbose_name_plural': 'Batch Commands'},
        ),
    ]
