# Generated by Django 5.0.9 on 2025-05-10 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_label_label_unique_language_per_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='fetched_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
