# Generated by Django 5.0.9 on 2025-06-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_label_fetched_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcommand',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
