# Generated by Django 5.0.9 on 2025-06-09 20:09

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_batchcommand_labels_delete_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='wikibase',
            field=models.ForeignKey(default=core.models.get_default_wikibase, on_delete=django.db.models.deletion.CASCADE, to='core.wikibase'),
        ),
    ]
