# Generated by Django 5.0.9 on 2025-07-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_batch_wikibase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='batchcommand',
            new_name='core_batchc_batch_i_88990f_idx',
            old_fields=('batch', 'index'),
        ),
        migrations.AddIndex(
            model_name='batchcommand',
            index=models.Index(fields=['batch', 'status'], name='core_batchc_batch_i_4b8791_idx'),
        ),
    ]
