# Generated by Django 5.0.9 on 2025-12-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_batchcommand_batch_index_core_batchc_batch_i_88990f_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchEditingSession',
        ),
    ]
