# Generated by Django 5.0.9 on 2026-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_batchcommand_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcommand',
            name='operation',
            field=models.TextField(blank=True, choices=[('create_item', 'Create item'), ('create_property', 'Create property'), ('set_statement', 'Set statement'), ('create_statement', 'Create statement'), ('switch_statement_value', 'Switch statement value'), ('switch_statement_property', 'Switch statement property'), ('remove_statement_by_id', 'Remove statement by id'), ('remove_statement_by_value', 'Remove statement by value'), ('remove_qualifier', 'Remove qualifier'), ('remove_reference', 'Remove reference'), ('set_sitelink', 'Set sitelink'), ('set_label', 'Set label'), ('set_description', 'Set description'), ('remove_sitelink', 'Remove sitelink'), ('remove_label', 'Remove label'), ('remove_description', 'Remove description'), ('add_alias', 'Add alias'), ('remove_alias', 'Remove alias')], null=True),
        ),
    ]
